require("config.lazy")
require("dir1.tag")
require("dir1.lsp")
require("dir1.gitoption")
require("dir1.remap")
require("dir1.telescope")
--require("dir1.treesitter")
require("dir1.harpoon")


vim.keymap.set("n", "<leader>u", vim.cmd.UndotreeToggle)
-- require("mason").setup()
require("oil").setup()
vim.keymap.set("n", "-", "<CMD>Oil<CR>", { desc = "Open parent directory" })
vim.opt.guifont = "FiraCode Nerd Font:h12"
vim.diagnostic.config({ virtual_text = { current_line = true } })
vim.keymap.set("n", "<leader>WW", function()
	vim.diagnostic.config({ virtual_text = { severity = vim.diagnostic.severity.ERROR } })
end, { desc = "Show only error diagnostics" })
vim.keymap.set("n", "<leader>WE", function()
	vim.diagnostic.config({ virtual_text = true })
end, { desc = "Show only error diagnostics" })
